### ISSUE TITLE
Change license to "AGPLv3 or later"

### ISSUE THREAD

**Issue by pizzamaker** [tuxxus/fediverse.org#2]
AGPLv3 closes a loophole regarding web apps. It is a stronger copyleft license. I suggest you skim its Wikipedia article: https://en.wikipedia.org/wiki/GNU_Affero_General_Public_License

**Comment by abjectio** [comment]
? isn't it AGPL - or? -> https://github.com/tuxxus/fediverse.org/blob/master/LICENSE

**Comment by pizzamaker** [comment]
Oops, you're right, I misread!
